# Generated by Django 6.0.7 on 2026-07-26 16:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['-date', '-time']},
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='department',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.IntegerField(choices=[(1, '1st Year'), (2, '2nd Year'), (3, '3rd Year'), (4, '4th Year')], default=1),
        ),
        migrations.CreateModel(
            name='FacultyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('is_approved', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlertConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail_address', models.EmailField(blank=True, max_length=254)),
                ('gmail_app_password', models.CharField(blank=True, max_length=64)),
                ('alert_threshold', models.IntegerField(default=75, help_text='Students below this attendance % will receive an alert.')),
                ('email_alerts_enabled', models.BooleanField(default=True)),
                ('alert_email_subject', models.CharField(default='URGENT: Low Attendance Warning', max_length=200)),
                ('alert_email_body', models.TextField(default='Dear Parent/Guardian,\n\nThis is an automated alert from the University Attendance System.\nYour ward {student_name} currently has {attendance_percentage}% attendance, which is below the mandatory {threshold}% threshold.\n\nPlease contact the administration immediately.\n\nRegards,\nUniversity Administration')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_config', to='core.facultyprofile')),
            ],
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaves_reviewed', to='core.facultyprofile'),
        ),
        migrations.AddField(
            model_name='student',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_added', to='core.facultyprofile'),
        ),
    ]
