# Generated by Django 6.0.7 on 2026-07-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_attendancerecord_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertconfiguration',
            name='sms_alert_body',
            field=models.TextField(default='URGENT: {student_name} has {attendance_percentage}% attendance (below {threshold}%). Contact administration.'),
        ),
        migrations.AddField(
            model_name='alertconfiguration',
            name='sms_alerts_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='alertconfiguration',
            name='twilio_account_sid',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='alertconfiguration',
            name='twilio_auth_token',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='alertconfiguration',
            name='twilio_from_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
