# Generated by Django 6.0.7 on 2026-09-22 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alertconfiguration_sms_alert_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="pin_code",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AlterField(
            model_name="alertconfiguration",
            name="gmail_app_password",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="alertconfiguration",
            name="twilio_auth_token",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="attendancerecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("Present", "Present"),
                    ("Absent", "Absent"),
                    ("Excused", "Excused"),
                ],
                default="Present",
                max_length=15,
            ),
        ),
    ]
