# Generated by Django 6.0.7 on 2026-09-22 06:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_student_pin_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancerecord",
            name="date",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
