# Generated by Django 6.0.7 on 2026-09-28 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_attendancerecord_date"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HolidayCalendar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "name",
                    models.CharField(
                        help_text="Holiday or event name, e.g. 'Diwali'", max_length=200
                    ),
                ),
                (
                    "holiday_type",
                    models.CharField(
                        choices=[
                            ("National", "National Holiday"),
                            ("University", "University Holiday"),
                            ("Exam", "Examination / No Classes"),
                            ("Event", "Academic Event"),
                            ("Other", "Other"),
                        ],
                        default="University",
                        max_length=50,
                    ),
                ),
                ("synced_at", models.DateTimeField(auto_now=True)),
                ("synced_by_bot", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Holiday",
                "verbose_name_plural": "Holiday Calendar",
                "ordering": ["date"],
            },
        ),
        migrations.AddField(
            model_name="alertconfiguration",
            name="dean_email",
            field=models.EmailField(
                blank=True,
                help_text="Dean's email address for monthly HOD PDF reports.",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="alertconfiguration",
            name="hod_report_threshold",
            field=models.IntegerField(
                default=75,
                help_text="Students below this % are included in the monthly HOD report.",
            ),
        ),
        migrations.CreateModel(
            name="RPABotLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bot_name",
                    models.CharField(
                        choices=[
                            ("leave_processor", "Bot 1 — Auto-Leave Processor"),
                            ("hod_report", "Bot 2 — Monthly HOD PDF Report"),
                            ("holiday_sync", "Bot 3 — Holiday Sync"),
                            ("ptm_escalation", "Bot 4 — PTM Escalation"),
                            ("db_backup", "Bot 5 — Nightly DB Backup"),
                            ("alert_bot", "Existing — Weekly Alert Bot"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("partial", "Partial Success"),
                            ("failed", "Failed"),
                            ("running", "Running"),
                        ],
                        default="running",
                        max_length=20,
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "summary",
                    models.TextField(
                        blank=True, help_text="Human-readable result summary."
                    ),
                ),
                ("records_processed", models.IntegerField(default=0)),
                (
                    "errors",
                    models.TextField(
                        blank=True, help_text="Any error messages encountered."
                    ),
                ),
                (
                    "triggered_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="The faculty user who triggered this bot run.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "RPA Bot Log",
                "verbose_name_plural": "RPA Bot Logs",
                "ordering": ["-started_at"],
            },
        ),
    ]
