# Generated by Django 6.0.7 on 2026-10-02 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_holidaycalendar_alertconfiguration_dean_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaveapplication",
            name="approved_by_bot",
            field=models.BooleanField(
                default=False,
                help_text="True if Bot 1 (Auto-Leave Processor) approved this leave automatically.",
            ),
        ),
        migrations.CreateModel(
            name="BotActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bot_name",
                    models.CharField(
                        choices=[
                            ("leave_processor", "🤖 Bot 1 — Auto-Leave Processor"),
                            ("hod_report", "📄 Bot 2 — HOD PDF Report"),
                            ("holiday_sync", "📅 Bot 3 — Holiday Sync"),
                            ("ptm_escalation", "🚨 Bot 4 — PTM Escalation"),
                            ("db_backup", "💾 Bot 5 — Nightly Backup"),
                            ("alert_bot", "📧 Alert Bot"),
                            ("face_recognition", "📷 Face Recognition"),
                            ("system", "⚙️ System"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        help_text="Short, human-readable description of the action.",
                        max_length=300,
                    ),
                ),
                (
                    "target",
                    models.CharField(
                        blank=True,
                        help_text="The entity acted upon, e.g. student name or table.",
                        max_length=200,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                        ],
                        default="info",
                        max_length=20,
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "detail",
                    models.TextField(
                        blank=True, help_text="Optional extra detail or error message."
                    ),
                ),
                (
                    "rpa_log",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activity_logs",
                        to="core.rpabotlog",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bot Activity Log",
                "verbose_name_plural": "Bot Activity Logs",
                "ordering": ["-timestamp"],
            },
        ),
    ]
