import os
from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer
from reportlab.lib.enums import TA_CENTER

class ReportLibrary:
    """
    Robot Framework Library for generating professional PDF reports using ReportLab.
    Eliminates fragile shell script / python -c inline invocations.
    """
    def generate_hod_pdf_report(self, output_path, students, threshold, report_date):
        """
        Builds a styled PDF table of at-risk students below the attendance threshold.
        """
        output_dir = os.path.dirname(os.path.abspath(output_path))
        os.makedirs(output_dir, exist_ok=True)

        doc = SimpleDocTemplate(output_path, pagesize=A4, topMargin=1.5*cm, bottomMargin=1.5*cm)
        styles = getSampleStyleSheet()

        title_style = ParagraphStyle(
            'Title',
            parent=styles['Heading1'],
            alignment=TA_CENTER,
            fontSize=16,
            textColor=colors.HexColor('#1a1a2e')
        )
        sub_style = ParagraphStyle(
            'Sub',
            parent=styles['Normal'],
            alignment=TA_CENTER,
            fontSize=10,
            textColor=colors.grey
        )

        elements = []
        elements.append(Paragraph('Monthly Attendance Risk Report', title_style))
        elements.append(Paragraph(f'University Attendance System | Report Date: {report_date}', sub_style))
        elements.append(Paragraph(f'Students Below {threshold}% Attendance Threshold | Total At-Risk: {len(students)}', sub_style))
        elements.append(Spacer(1, 0.5*cm))

        headers = ['#', 'Student Name', 'Enrollment No.', 'Department', 'Year', 'Parent Email', 'Attendance %']
        table_data = [headers]

        for idx, row in enumerate(students, 1):
            name, enr, dept, year, parent_email, pct = row
            table_data.append([
                str(idx),
                str(name),
                str(enr),
                str(dept) if dept else 'N/A',
                f'Year {year}',
                str(parent_email),
                f'{pct}%'
            ])

        col_widths = [1*cm, 4*cm, 3.5*cm, 3.5*cm, 1.8*cm, 5*cm, 2.5*cm]
        t = Table(table_data, colWidths=col_widths, repeatRows=1)
        t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.HexColor('#1a1a2e')),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,0), 9),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor('#f8f9fa')]),
            ('FONTSIZE', (0,1), (-1,-1), 8),
            ('GRID', (0,0), (-1,-1), 0.3, colors.lightgrey),
            ('TOPPADDING', (0,0), (-1,-1), 6),
            ('BOTTOMPADDING', (0,0), (-1,-1), 6),
        ]))
        elements.append(t)
        elements.append(Spacer(1, 0.5*cm))
        elements.append(Paragraph('<i>This report was auto-generated by the University RPA Attendance Bot. Do not reply to this email.</i>', sub_style))

        doc.build(elements)
        print(f"✅ PDF successfully generated at: {output_path} ({os.path.getsize(output_path)} bytes)")
        return output_path
